frontend/controllers/UserwallController.php
<?php
namespace frontend\controllers;
use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\mongodb\ActiveRecord;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use frontend\models\PostForm;
use frontend\models\PlaceDiscussion;
use frontend\models\PlaceReview;
use frontend\models\LoginForm;
use frontend\models\Comment;
use frontend\models\UserForm; 
use frontend\models\Like;
use frontend\models\Page;
use frontend\models\Friend;
use frontend\models\Personalinfo;
use frontend\models\ProfileVisitor;
use frontend\models\SecuritySetting;
use frontend\models\SavePost;
use frontend\models\Interests;
use frontend\models\Language;
use frontend\models\Occupation;
use frontend\models\Notification;
use frontend\models\MuteFriend;
use frontend\models\BlockFriend;
use frontend\models\UnfollowFriend;
use frontend\models\TurnoffNotification;
use frontend\models\PinImage;
use frontend\models\ReferForm;
use frontend\models\Vip;
use frontend\models\Verify;
use frontend\models\Group;
use frontend\models\Collection;
use frontend\models\Credits;
use frontend\models\CountryCode;
use frontend\models\Education;
use frontend\models\Destination;
use frontend\models\SliderCover;
use frontend\models\UserPhotos;
use frontend\models\PlaceAsk;
use frontend\models\PlaceTip;
use frontend\models\PageReviewPhotos;
use frontend\models\Userwallgallery;
use frontend\models\Gallery;

class UserwallController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }
    
    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action);
    }
	
    public function actions()
    {
        return [
        'auth' => [
          'class' => 'yii\authclient\AuthAction',
          'successCallback' => [$this, 'oAuthSuccess'],
        ],
            'captcha' => [
            'class' => 'yii\captcha\CaptchaAction',
        ],        
     ];           
    }
  
    public function actionIndex()
    { 
        $session = Yii::$app->session;
        $request = Yii::$app->request;
        $user_id = $request->get('id'); 
        $uid = (string)$session->get('user_id');	

            if(isset($uid) && $uid != '') { 
            	$checkuserauthclass = UserForm::isUserExistByUid($uid); 
            } else {
            	$checkuserauthclass = 'checkuserauthclassg';
            } 
		
        	$emails = $session->get('email');
            $user_exist = LoginForm::find()->where(['email' => $emails])->andwhere(['not','status','44'])->asarray()->one();
            $visitor_id = (string)$user_exist['_id'];
			
			$block = BlockFriend::find()->where(['user_id' => "$user_id"])->andwhere(['like','block_ids',$visitor_id])->one();
			if(!$block)
			{
				if($user_id != $visitor_id)
				{
					$visitors = ProfileVisitor::find()->select(['_id'])->with('user')->where(['user_id' => "$user_id",'visitor_id' => $visitor_id,'year' => date("Y"),'month' => date("M")])->one();
					$date = time();

					if($visitors)
					{
						$visitors->visited_date = "$date";
						$visitors->update();
					}
					else
					{
						$visitor = new ProfileVisitor();
						$visitor->user_id = $user_id;
						$visitor->visitor_id = $visitor_id;
						$visitor->visited_date = "$date";
						$visitor->status = '1';
						$visitor->ip = $_SERVER['REMOTE_ADDR'];
						$visitor->month = date("M");
						$visitor->year = date("Y");
						$visitor->insert();
					}
				}

				$user_data =  Personalinfo::getPersonalInfo($user_id);

				$user_friends =  Friend::getuserFriends($user_id);
                $user_friends = array_slice($user_friends, 0, 6);

				$user_tags =  Friend::getuserFriends($request->get('id'));

				$user_basicinfo = LoginForm::find()->where(['_id' => $user_id])->one();

				$posts = PostForm::getUserPostUserwall($user_id);

				$photos =  UserPhotos::getUserPostPhotos($user_id);
                
				$likes = Like::getUserPostLike($user_id);

				$path = 'profile/';
				$usrfrdlist = array();
				foreach($user_tags AS $ud) {
					$id = (string)$ud['userdata']['_id'];
					$fbid = isset($ud['userdata']['fb_id']) ? $ud['userdata']['fb_id'] : '';
					$dp = $this->getimage($ud['userdata']['_id'],'thumb');
					
					$nm = (isset($ud['userdata']['fullname']) && !empty($ud['userdata']['fullname'])) ? $ud['userdata']['fullname'] : $ud['userdata']['fname'].' '.$ud['userdata']['lname'];
					$usrfrdlist[] = array('id' => $id, 'fbid' => $fbid, 'name' => $nm, 'text' => $nm, 'thumb' => $dp);
				}

				return $this->render('index',array('posts' => $posts,'user_friends' => $user_friends,'photos' => $photos,'user_basicinfo' => $user_basicinfo,'user_data' => $user_data,'likes' => $likes, 'usrfrdlist' => $usrfrdlist, 'checkuserauthclass' => $checkuserauthclass));
			} else {
				$this->redirect(Url::toRoute(['site/block','blockid'=>$user_id]));
			}
    }
    
    public function actionPhotos()
    {
       $session = Yii::$app->session;
       $request = Yii::$app->request;
       $user_id = $request->get('id');  
       $userid = $session->get('user_id');
       $secureity_model = new SecuritySetting();
       $result_security = SecuritySetting::find()->select(['view_photos'])->where(['user_id' => (string)$userid])->asarray()->one();
       if($result_security)
        {
            $album_privacy = $result_security['view_photos'];
       }
       else
       {
           $album_privacy = 'Public';
       }
    
       $model = new \frontend\models\LoginForm();

        $post = new UserPhotos();
        $isNewAlbum =  false;
        $page_id = '';
        if(strstr($_SERVER['HTTP_REFERER'],'r=page'))
        {
            $url = $_SERVER['HTTP_REFERER'];
            $url = explode('&',$url);
            $url = explode('=',$url[1]);
            $page_id = $url[1];

            $getPageData = Page::find()->where([(string)'_id' => $page_id])->asarray()->one();
            if(!empty($getPageData)) {
                $gen_photos = isset($getPageData['gen_photos']) ? $getPageData['gen_photos'] : '';
                $gen_photos_review = isset($getPageData['gen_photos_review']) ? $getPageData['gen_photos_review'] : '';
                if($gen_photos == 'allowPhotos' && $gen_photos_review == 'on') {
                    $post = new PageReviewPhotos();                    
                    $isNewAlbum =  true;
                }
            }
        }
        
        $date = time();
        if($session->get('email'))
        {
            if(isset($_POST) && !empty($_POST)){
            $album_title = $_POST['album_title'];
            if(empty($album_title)){$album_title = 'Untitled Album';}
            $album_description = $_POST['album_description'];
            $album_place = $_POST['album_place'];
            $album_img_date = '';  
            $post->post_status = '1'; 
            $post->album_title = ucfirst($album_title);
            $post->post_text = $album_description;
            $post->album_place = $album_place;
            $post->album_img_date = $album_img_date;
            $post->post_type = 'text and image'; 
            $post->is_album = '1';
            $post->post_privacy = $album_privacy;
            $post->post_created_date = "$date";
            $post->is_deleted = '0';
            if(strstr($_SERVER['HTTP_REFERER'],'r=page'))
            {
                $page_details = Page::Pagedetails($page_id);
                $userid = $page_id;
                $post->post_privacy = 'Public';
                $puid = (string)$session->get('user_id');
                $post->shared_by = "$puid"; 
                $post->pagepost = '1';
                $post->is_deleted = "0";
                if($isNewAlbum) {
                    $post->isnewalbum = true;
                    $post->page_id = $page_id;
                }
            }
            else
            {
                $userid = $userid;
            }
            $post->post_user_id = (string)$userid;
            $post->post_ip = $_SERVER['REMOTE_ADDR'];
            
             if(isset($_FILES) && !empty($_FILES)){
                $imgcount = count($_FILES["imageFile1"]["name"]);
                $img = '';
                $im = '';
                for($i=0; $i<$imgcount; $i++)
                {
					if(isset($_FILES["imageFile1"]["name"][$i]) && $_FILES["imageFile1"]["name"][$i] != "") 
					{
					   $url = '../web/uploads/';
					   $urls = '/uploads/';
                       $image_extn = explode('.',$_FILES["imageFile1"]["name"][$i]);
                       $image_extn = end($image_extn);
					   $rand = rand(111,999);
					   $img = $urls.$date.$rand.'.'.$image_extn.',';
					   move_uploaded_file($_FILES["imageFile1"]["tmp_name"][$i], $url.$date.$rand.'.'.$image_extn);

					   $im = $im . $img;
					}
                }
              
                $post->image = $im;
            }
            $post->insert();
            $last_ablum_id = $post->_id;

            if($album_privacy != 'Public')
            {
                $notification = new Notification();
                $notification->post_id = "$last_ablum_id";
                $notification->user_id = "$userid";
                $notification->notification_type = 'post';
                $notification->is_deleted = '0';
                $notification->status = '1';
                $notification->created_date = "$date";

frontend/views/userwall/activitylog.php
<?php
$session = Yii::$app->session;
$user_id = (string) $session->get('user_id');  
?>
<div class="combined-column">												
	<div class="content-box nobg">
		<div class="cbox-title nborder maintitle">								
			<div class="subtitle"><h5>Activity Log</h5></div>
			<div class="right-tabs">
				<div class="friends-search">
					<div class="fsearch-form">
						<input type="text" placeholder="Search log text"/>
						<a href="javascript:void(0)"><i class="zmdi zmdi-search grey-text"></i></a>
					</div>
				</div>
			</div>
		</div>
		<div class="cbox-desc maindesc">
			<div class="activity-holder"> 
				<div class="content-box bshadow">
					<div class="cbox-title">
						Today
					</div>							
					<div class="cbox-desc" data-id="dels">
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<?php exit();?>

frontend/views/userwall/add_album_content.php
<div class="modal_content_container">
	<div class="modal_content_child modal-content">
		<div class="popup-title ">
			<button class="hidden_close_span close_span waves-effect">
				<i class="mdi mdi-close mdi-20px compose_discard_popup"></i>
			</button>			
			<h3>Create new album</h3>
			<a type="button" class="item_done crop_done waves-effect hidden_close_span custom_close" href="javascript:void(0)" >Done</a>
		</div>
	
		<div class="custom_modal_content modal_content" id="createpopup">
			<div class="ablum-yours profile-tab">
				<div class="ablum-box detail-box">															
					<div class="content-holder main-holder">
						<div class="summery">																	
							<div class="dsection bborder expandable-holder expanded">	
								<div class="form-area expandable-area">
									<form class="ablum-form">
										<div class="form-box">
											<div class="fulldiv">
												<div class="half">
													<div class="frow">
														<div class="caption-holder">
															<label>Album title</label>
														</div>
														<div class="detail-holder">
															<div class="input-field">
																<input type="text" class="fullwidth locinput" placeholder="Album title" name="album_title" id="album_title">
															</div>
														</div>
													</div>
												</div>
											</div>
											
											<div class="fulldiv">
												<div class="half">
													<div class="frow">
														<div class="caption-holder">
															<label>Say something about it</label>
														</div>
														<div class="detail-holder">
															<div class="input-field">
																<input type="text" placeholder="Tell people about the album" name="album_description" class="fullwidth locinput" id="album_description"/>
															</div>
														</div>
													</div>
												</div>
											</div>
											
											<div class="fulldiv">
												<div class="half">
													<div class="frow">
														<div class="caption-holder">
															<label>Where was it taken?</label>
														</div>
														<div class="detail-holder">
															<div class="input-field">
																<input type="text" name="album_place" placeholder="Where was it taken?" class="fullwidth locinput getplacelocation" data-query="all"  onfocus="filderMapLocationModal(this)" id="album_place"/>
															</div>
														</div>
													</div>
												</div>
											</div>
											
											<div class="frow nomargin new-post">
												<div class="caption-holder">
													<label>Add photos to album</label>
												</div>
												<div class="detail-holder">
													<div class="input-field ">					
														<div class="post-photos new_pic_add">
															<div class="img-row">		
																<div class="img-box">
																	<div class="custom-file addimg-box add-photo ablum-add">
																	<span class="icont">+</span><br><span class="">Upload photo</span>
																	<div class="addimg-icon">
																	</div>

																	<input type="file" name="imageFile1[]" class="upload custom-upload remove-custom-upload custom-upload-new" title="Choose a file to upload xx" required="true" data-class="#addAlbumContentPopup .post-photos .img-row" multiple="true"/>
																	</div>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>											
									</form>
								</div>
							</div>													
						</div>																
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="valign-wrapper additem_modal_footer modal-footer">		
	<a href="javascript:void(0)" class="btngen-center-align  close_modal open_discard_modal waves-effect">Cancel</a>
	<a href="javascript:void(0)" class="btngen-center-align waves-effect" data-class="addbtn" onclick="addAlbum()">Create</a>
</div>
<?php exit; ?>

frontend/views/userwall/dest_list.php
<?php
use frontend\assets\AppAsset;
use frontend\models\PostForm;
use frontend\models\PhotoForm;
$baseUrl = AppAsset::register($this)->baseUrl;
?>
	<div class="gloader"><img src="<?=$baseUrl?>/images/loading.gif" class="g-loading"/></div>
	<div id="destigrid">
		<?php array_push($dest,$place);
			foreach($dest as $destination) {
			if(!isset($destination['_id']))
			{
				$destinationid = rand(1000,9999);
				$destinationname = str_replace("'","",$place);
			}
			else
			{
				$destinationid = $destination['_id'];
				$destinationname = str_replace("'","",$destination['place']);
			}
			$count = substr_count($destinationname,",");
			if($count >= 1)
			{
				$placet = (explode(",",$destinationname));
				$placefirst = $placet[0];
				$placesecond = $placet[1];
				if(isset($placet[2]) && !empty($placet[2]))
				{
					$placesecond .=', '.$placet[2];
				}
			}
			else
			{
				$placet = (explode(",",$destinationname));
				$placefirst = $placet[0];
				$placesecond = '&nbsp;';
			}
			$getpplacereviews = PostForm::getPlaceReviewsCount($destinationname,'reviews');
			$getpplacereasks = PostForm::getPlaceReviewsCount($destinationname,'ask');
			$getpplacerephotos = PhotoForm::getTotalPics($destinationname);
			$getpplacetips = PostForm::getPlaceReviewsCount($destinationname,'tip');
			$destimage = $this->context->getplaceimage($destinationname);
		?>
		<div class="wcard">
			<div class="desc-holder">
				<div class="sumbox">
					Reviews<span><?=$getpplacereviews?></span>
				</div>
				<div class="sumbox">
					Ask<span><?=$getpplacereasks?></span>
				</div>
				<div class="sumbox">
					Photos<span><?=$getpplacerephotos?></span>
				</div>
				<div class="sumbox">
					Tips<span><?=$getpplacetips?></span>
				</div>
			</div>
			<div class="img-holder">
				<a href="?r=places&p=<?=$destinationname?>" target="_blank">
					<img alt="" src="<?=$destimage?>">
				</a>
				<div class="ititle">
					<div class="ititle-icon"><i class="mdi-map"></i></div>
					<div class="ititle-text">
						<?=$placefirst?>
						<span>
							<?=$placesecond?>
						</span>
					</div>
					<a class="ititle-extra" href="javascript:void(0)"></a>
				</div>
			</div>
			
			<div class="img-holder dis-none" data-id="strcube">
				<a href="?r=places&p=" target="_blank">
					<img alt="" src="<?=$destimage?>">
				</a>
				<div class="ititle">
					<div class="ititle-icon"><i class="mdi-map"></i></div>
					<div class="ititle-text">
						
						<span>
							
						</span>
					</div>
					<a class="ititle-extra" href="javascript:void(0)"><i class="zmdi zmdi-pin"></i></a>
				</div>
			</div>
			
		</div>
		<?php } ?>
	</div>
<?php exit();?>

frontend/views/userwall/dest_map.php
<?php
use frontend\assets\AppAsset;
use frontend\models\PostForm;
use frontend\models\PhotoForm;
use frontend\models\Personalinfo;
$baseUrl = AppAsset::register($this)->baseUrl;
$user_data = Personalinfo::find()->where(['user_id' => (string)$wall_user_id])->one();
$visited_countries = $user_data['visited_countries'];
if($user_data['visited_countries']=='null'){$user_data['visited_countries']='';}
$visited_str = '';
if(isset($visited_countries) && $visited_countries != '') {
	$visited_str = explode(",",$visited_countries);
}

if($user_id == $wall_user_id) {
	$visited_cities = '';

	array_push($destpast,$place);
	if(isset($visited_str) && !empty($visited_str))
	{
		$destpast = array_merge($destpast,$visited_str);
	}

	foreach($destpast as $destination){
		if(!isset($destination['_id']))
		{
			$destinationid = rand(1000,9999);
			$destinationname = str_replace("'","",$destination);
		}
		else
		{
			$destinationid = $destination['_id'];
			$destinationname = str_replace("'","",$destination['place']);
		}
		$count = substr_count($destinationname,",");
		if($count >= 1)
		{
			$placet = (explode(",",$destinationname));
			$placefirst = $placet[0];
			$placesecond = $placet[1];
			if(isset($placet[2]) && !empty($placet[2]))
			{
				$placesecond .=', '.$placet[2];
			}
		}
		else
		{
			$placet = (explode(",",$destinationname));
			$placefirst = $placet[0];
			$placesecond = '&nbsp;';
		}
		$destimage = $this->context->getplaceimage($destinationname);
		$getdestlatlng = $this->context->getlatlng($destinationname);
		$visited_cities .=  "['".$destinationname."',".$getdestlatlng.",'".$destimage."'],";
	} 
	$visited_cities = substr($visited_cities,0,-1);
} else { 
	$visited_cities = '';
	foreach($destpast as $destination)
	{
		$destinationid = $destination['_id'];
		$destinationname = str_replace("'","",$destination['place']);
		$count = substr_count($destinationname,",");
		if($count >= 1)
		{
			$placet = (explode(",",$destinationname));
			$placefirst = $placet[0];
			$placesecond = $placet[1];
			if(isset($placet[2]) && !empty($placet[2]))
			{
				$placesecond .=', '.$placet[2];
			}
		}
		else
		{
			$placet = (explode(",",$destinationname));
			$placefirst = $placet[0];
			$placesecond = '&nbsp;';
		}
		$destimage = $this->context->getplaceimage($destinationname);
		$getdestlatlng = $this->context->getlatlng($destinationname);
		$visited_cities .=  "['".$destinationname."',".$getdestlatlng.",'".$destimage."'],";
	}
	$getcurrent = $this->context->getlatlng($place);
	$destimagee = $this->context->getplaceimage($place);
	$visited_cities .=  "['".str_replace("'","",$place)."',".$getcurrent.",'".$destimagee."'],";
	$visited_cities = substr($visited_cities,0,-1);
}
	$visit_cities = '';
	foreach($destfuture as $destination)
	{
		$destinationid = $destination['_id'];
		$destinationname = str_replace("'","",$destination['place']);
		$count = substr_count($destinationname,",");
		if($count >= 1)
		{
			$placet = (explode(",",$destinationname));
			$placefirst = $placet[0];
			$placesecond = $placet[1];
			if(isset($placet[2]) && !empty($placet[2]))
			{
				$placesecond .=', '.$placet[2];
			}
		}
		else
		{
			$placet = (explode(",",$destinationname));
			$placefirst = $placet[0];
			$placesecond = '&nbsp;';
		}
		$destimage = $this->context->getplaceimage($destinationname);
		$getdestlatlng = $this->context->getlatlng($destinationname);
		$visit_cities .=  "['".$destinationname."',".$getdestlatlng.",'".$destimage."'],";
	}
	$visit_cities = substr($visit_cities,0,-1);
	$getcurrent = $this->context->getlatlng($place);
	$destimagee = $this->context->getplaceimage($place);
	$getspain = $this->context->getlatlng('Spain');
?>
	<div class="map-holder">
		<div class="mapdiv" id="destmap"></div>
		<div class="mapkeys">
			<ul>
				<li><span class="greenkey"></span> Visited</li>
				<li><span class="orangekey"></span> Want to visit</li>
				<li><span class="redkey"></span> Current</li>
			</ul>
		</div>
		<script>
			var places={
				visited:{
					label:' Visited',
					icon: '<?=$baseUrl?>/images/green-locicon.png',
					items: [<?=$visited_cities?>]
				},
				want:{
					label:' Want to visit',
					icon: '<?=$baseUrl?>/images/orange-locicon.png',
					items: [<?=$visit_cities?>]
				},
				current:{
					label:' Current location',
					icon: '<?=$baseUrl?>/images/red-locicon.png',
					items: [
						['<?=str_replace("'","",$place)?>', <?=$getcurrent?>, '<?=$destimagee?>']
					]
				}
			},
			map = new google.maps.Map(
				document.getElementById('destmap'), 
				{
					zoom: 2,
					center: new google.maps.LatLng(<?=$getspain?>),
				}
			),
			infowindow = new google.maps.InfoWindow(),
			ctrl=$('<div/>').css({background:'#fff',
				border:'1px solid #000',
				padding:'4px',
				margin:'2px',
				textAlign:'center'
			   });
			ctrl.append($('<input>',{type:'button',id:'showall',value:'Show'})
				.click(function(){
				  $(this).parent().find('input[type="checkbox"]')
					.prop('checked',true).trigger('change');
				}));
			//ctrl.append($('<br/>'));
			ctrl.append($('<input>',{type:'button',value:'Clear'})
				.click(function(){
				  $(this).parent().find('input[type="checkbox"]')
					.prop('checked',false).trigger('change');
				}));
			//ctrl.append($('<hr/>'));
			$.each(places,function(c,category){
				var cat=$('<input>',{type:'checkbox',checked:true}).change(function(){
				   $(this).data('goo').set('map',(this.checked)?map:null);
				})
				.data('goo',new google.maps.MVCObject)
				.prop('checked',category.checked)
				.trigger('change')
				.appendTo($('<div/>').css({whiteSpace:'nowrap',textAlign:'left'}).appendTo(ctrl))
				.after(category.label);
				$.each(category.items,function(m,item){
					/*var image = new google.maps.MarkerImage(
						item[3],
						// This marker is 20 pixels wide by 32 pixels tall.
						new google.maps.Size(20, 32));*/
					var marker=new google.maps.Marker({
						position:new google.maps.LatLng(item[1],item[2]),
						title:item[0],
						icon:category.icon
						//icon:image
					});
					marker.bindTo('map',cat.data('goo'),'map');
					google.maps.event.addListener(marker,'click',function(){
						infowindow.setContent(item[0]);
						infowindow.open(map,this);
					});
				});
			});
			map.controls[google.maps.ControlPosition.TOP_RIGHT].push(ctrl[0]);
		</script>
	</div>
<?php exit();?>

frontend/views/userwall/dest_visit_list.php
<?php
use frontend\assets\AppAsset;
use frontend\models\Personalinfo;
$baseUrl = AppAsset::register($this)->baseUrl;
$visit_cities = '';
$visited_cities = '';
if(!empty($destpast)) { ?>
<ul class="dest-list nice-scroll">
	<?php
	//array_push($destpast,$place);
	if(isset($visited_str) && !empty($visited_str)) {
		$destpast = array_merge($destpast,$visited_str);
	}

	foreach($destpast as $destination) {
		if(!isset($destination['_id'])) {
			$destinationid = rand(1000,9999);
			$destinationname = str_replace("'","",$destination);
		} else {
			$destinationid = $destination['_id'];
			$destinationname = str_replace("'","",$destination['place']);
		}

		$count = substr_count($destinationname,",");
		if($count >= 1) {
			$placet = (explode(",",$destinationname));
			$placefirst = $placet[0];
			$placesecond = $placet[1];
			if(isset($placet[2]) && !empty($placet[2]))
			{
				$placesecond .=', '.$placet[2];
			}
		} else {
			$placet = (explode(",",$destinationname));
			$placefirst = $placet[0];
			$placesecond = '&nbsp;';
		}
		$destimage = $this->context->getplaceimage($destinationname);
		$getdestlatlng = $this->context->getlatlng($destinationname);
		$visited_cities .=  "['".$destinationname."',".$getdestlatlng.",'".$destimage."'],";
		$time = time();
		$rand = rand(999, 999999);
		$getkey = $time.'_'.$rand;
		?>
		<li id="XHIL<?=$getkey?>">
			<div class="destili">
				<div class="imgholder himg-box">
					<img src="<?=$destimage?>" class="himg"/>
				</div>
				<div class="descholder">
					<h6><a href="?r=places&p=<?=$destinationname?>" target="_blank"><?=$placefirst?></a><span><?=$placesecond?></span></h6>
					<span class="beenthere">Been there</span>
					<?php if(isset($destination['_id'])) { ?>
					<a href="javascript:void(0)" onclick="delDest('<?=$destinationid?>', '#XHIL<?=$getkey?>')" class="cross">
						<i class="mdi mdi-close	"></i>
					</a>
					<?php } ?>
				</div>
			</div>
		</li>
		<?php 
	} 
	$visited_cities = substr($visited_cities,0,-1); ?>
</ul>
<?php } ?>
<div class="clear"></div>
<div class="add-dest">
	<div class="sliding-middle-custom anim-area underlined fullwidth locinput">
	<input data-query="M" id="past" class="validate getplacelocation" onfocus="filderMapLocationModal(this)" autocomplete="off" placeholder="Add place you have been to" type="text">
	</div>

	<a href="javascript:void(0)" class="btn-custom waves-effect" onclick="addDest('past')">Add</a>
</div>
<?php exit();?>

frontend/views/userwall/ranking.php
<?php
use yii\helpers\Url;
?>
<div class="cbox-title">
	<span><?= $this->context->getuserdata($wall_user_id,'fullname');?>'s</span>Ranking
</div>
<div class="cbox-desc">
	<div class="databox">
		<div class="meter-holder">
			<div class="gauge3 ranking-meter"></div>
			<h6><span>Points</span> <?= $point_total;?></h6>
		</div>
	</div>										
</div>
<div class="division"></div>

<div class="cbox-title">
	Top Rankers
</div>
<div class="cbox-desc">							
	<div class="resizable-holder sidelist">
		<div class="resizable">
			<ul class="rankers-list">
			<?php
				$i = 1;
				foreach($users as $user){
					if($user['point_total']){
						$user_id =  $user['_id'];
			?>	
					<li>
						<div class="ranker-box">
							<div class="img-holder"><img src="<?= $this->context->getimage($user_id,'photo');?>"/></div>
							<div class="desc-holder">
								<a href="<?php $ids = $user_id; echo Url::to(['userwall/index', 'id' => "$ids"]); ?>"><?= $this->context->getuserdata($user_id,'fullname');?></a>	
								<span class="info"><?= $this->context->getuserdata($user_id,'city');?></span>
							</div>								
						</div>							
					</li>
			<?php
					$i++;
					}
				}
			?>	
			</ul>
		</div>
		<div class="right resize-link" onclick="openResizable(this)"><a href="javascript:void(0)">View All</a></div>
	</div>
</div>
<script>
$('.gauge3').gauge({
	values: {
		0 : '0%',
		25: '25% - 75%',
		100: '100%'
	},
	colors: {
		0 : '#ED1C24',
		25 : '#39B54A',
		75: '#FDD914'
	},
	angles: [
		180,
		360
	],
	lineWidth: 20,
	arrowWidth: 10,
	arrowColor: '#ccc',
	inset:true,

	value: '<?= $percent;?>'
});
</script>

<?php exit();?>